services:
  ingest_data:
    build: .
    container_name: sap_ingest_service
    command: python ingest_sap_data.py
    env_file: .env
    volumes:
      - .:/app
    networks:
      - sap-net

  train_model:
    build: .
    container_name: sap_train_service
    command: python train_model.py
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      ingest_data:
        condition: service_completed_successfully
    networks:
      - sap-net

  web_app:
    build: .
    container_name: sap_intel_app
    command: python app.py
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - train_model
    networks:
      - sap-net

  sap_scheduler:
    build: .
    container_name: sap_scheduler_service
    command: python sap_sync_service.py
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - train_model
    networks:
      - sap-net

networks:
  sap-net:
    driver: bridge