services:
  ingest_data:
    build: .
    container_name: sap_ingest_service
    command: python ingest_sap_data.py
    env_file: .env
    volumes:
      - .:/app 
    dns:
      - 8.8.8.8
    # Adding a timeout for the container itself
    stop_grace_period: 10s
    networks:
      - sap-net

  train_model:
    build: .
    container_name: sap_train_service
    command: python train_model.py
    env_file: .env
    volumes:
      - .:/app 
    dns:
      - 8.8.8.8
    depends_on:
      ingest_data:
        condition: service_started 
    networks:
      - sap-net

  web_app:
    build: .
    container_name: sap_intel_app
    command: python app.py
    volumes:
      - .:/app 
    ports:
      - "5000:5000"
    env_file: .env
    dns:
      - 8.8.8.8
    depends_on:
      - ingest_data 
    networks:
      - sap-net

networks:
  sap-net:
    driver: bridge